//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProject.Data.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int id { get; set; }
        public string name { get; set; }
        public int ingredientListID { get; set; }
        public string listOfDirections { get; set; }
        public string editHistory { get; set; }
    
        public virtual RecipeIngredientList RecipeIngredientList { get; set; }
    }
}
